edition = "2021"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"
# Note: imports_granularity and group_imports require nightly
# Uncomment when using nightly toolchain:
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
